### ISSUE TITLE
Key events for moving kara interfere with text input in blocks

### ISSUE THREAD

**Issue by complanar** [cgloeckner/blockly-kara#3]
Text input in Blocks (f.e. naming a function or a variable) swallows the characters e, a, w, s and d, seemingly because they are used in moving Kara.

Must limit these key controls to the world panel or suppress them, when the block panel is "focused".

**Comment by cgloeckner** [comment]
Same for changing the grid size (e.g. ctrl+a to select all digits in order to replace, this will trigger movement, too).

**Comment by cgloeckner** [comment]
Should be fixed by https://github.com/cgloeckner/blockly-kara/commit/f60b8e5c4ffd7aab90040ffbea5a6c89478df42c, please confirm @complanar

**Comment by complanar** [comment]
Seems to work. I did not encounter any more problems, at least no obvious ones. Double checked in mobile browsers. Seems to work, too.

Chromium based browsers on android have problems to get the app working in general, though. Firefox seems to be working.

**Comment by complanar** [comment]
> Chromium based browsers on android have problems to get the app working in general, though. Firefox seems to be working.

Nevermind. Can not reproduce anymore.
